name = "tetra-ecosystem-olympic"
compatibility_date = "2024-09-01"
pages_build_output_dir = "."

[env.production]
workers_dev = false

[[routes]]
pattern = "tetra-ecosystem.com/*"
custom_domain = true
